version: '3.9'

services:
    message-broker:
        image: rabbitmq:3-management-alpine
        container_name: message-broker
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./data/rabbitmq/data/:/var/lib/rabbitmq
            - ./data/rabbitmq/log/:/var/log/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: test
            RABBITMQ_DEFAULT_PASS: test
        networks:
            - dev-network
    producer:
        container_name: producer
        build:
            context: ./producer
            dockerfile: Dockerfile
        environment:
            AMQP_SERVER_URL: amqp://test:test@message-broker:5672/
        networks:
            - dev-network
        depends_on:
            - message-broker
    consumer-1:
        container_name: consumer-1
        build:
            context: ./consumer-1
            dockerfile: Dockerfile
        environment:
            AMQP_SERVER_URL: amqp://test:test@message-broker:5672/
        networks:
            - dev-network
        depends_on:
            - message-broker
            - producer
    consumer-2:
        container_name: consumer-2
        build:
            context: ./consumer-2
            dockerfile: Dockerfile
        environment:
            AMQP_SERVER_URL: amqp://test:test@message-broker:5672/
        networks:
            - dev-network
        depends_on:
            - message-broker
            - producer

networks:
    dev-network:
        driver: bridge
